# Generated by Django 5.2.8 on 2025-11-26 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "google_sub",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("saved_items", models.JSONField(default=list)),
                ("basic_information", models.JSONField(default=dict)),
                ("interests", models.JSONField(default=list)),
                ("goals", models.JSONField(default=list)),
                ("other_goals", models.TextField(blank=True, null=True)),
                ("finished_onboarding", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
