# Generated by Django 5.2.7 on 2025-10-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_user_usermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="saved_items",
            field=models.JSONField(default=list),
        ),
    ]
