# Generated by Django 5.2.7 on 2025-10-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
