# Generated by Django 5.2.7 on 2025-10-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_usermodel_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="finished_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
