# Generated by Django 5.2.7 on 2025-10-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_usermodel_finished_onboarding"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermodel",
            old_name="tags",
            new_name="goals",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="basic_information",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="interests",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="other_goals",
            field=models.TextField(blank=True, null=True),
        ),
    ]
