# Generated by Django 5.2.8 on 2025-11-12 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_tags_usermodel_goals_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserModel",
            new_name="UserProfile",
        ),
    ]
