# Generated by Django 5.2.8 on 2025-11-14 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_user(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    User = apps.get_model("auth", "User")

    for profile in UserProfile.objects.all():
        if profile.email:
            try:
                profile.user = User.objects.get(email=profile.email)
                profile.save()
            except User.DoesNotExist:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_rename_usermodel_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(link_user),
    ]
