# Generated by Django 5.2.8 on 2025-11-26 10:02

from django.db import migrations, models

import pathfinder_api.vectordb


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuggestionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("category", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("description", models.TextField(default="")),
                ("url", models.URLField(default="", max_length=255)),
                (
                    "image",
                    models.URLField(
                        default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeJQeJyzgAzTEVqXiGe90RGBFhfp_4RcJJMQ&s",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("score", models.IntegerField(default=0)),
                (
                    "embedding",
                    pathfinder_api.vectordb.VectorField(default=[], dimensions=3),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuggestionsCacheModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_information", models.JSONField(default=dict)),
                ("interests", models.JSONField(default=list)),
                ("goals", models.JSONField(default=list)),
                ("other_goals", models.TextField(blank=True, null=True)),
                ("suggestions", models.JSONField(default=list)),
            ],
        ),
    ]
