# Generated by Django 5.2.7 on 2025-10-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuggestionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("url", models.URLField(max_length=255)),
                ("image_url", models.URLField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
