# Generated by Django 5.2.7 on 2025-10-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suggestionmodel",
            old_name="image_url",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="suggestionmodel",
            name="category",
            field=models.JSONField(default=list),
        ),
    ]
