# Generated by Django 5.2.7 on 2025-10-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0002_rename_image_url_suggestionmodel_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestionmodel",
            name="url",
            field=models.URLField(default="", max_length=255),
        ),
    ]
