# Generated by Django 5.2.7 on 2025-10-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0003_alter_suggestionmodel_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestionmodel",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="suggestionmodel",
            name="image",
            field=models.URLField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeJQeJyzgAzTEVqXiGe90RGBFhfp_4RcJJMQ&s",
                max_length=255,
            ),
        ),
    ]
