# Generated by Django 5.2.7 on 2025-11-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0005_add_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestionsCacheModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("basic_information", models.JSONField(default=dict)),
                ("interests", models.JSONField(default=list)),
                ("goals", models.JSONField(default=list)),
                ("other_goals", models.TextField(blank=True, null=True)),
                ("suggestions_ids", models.JSONField(default=list)),
            ],
        ),
    ]
