# Generated by Django 5.2.7 on 2025-11-06 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0006_suggestionscachemodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestionscachemodel",
            name="external_id",
        ),
    ]
