# Generated by Django 5.2.8 on 2025-11-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0007_remove_suggestionscachemodel_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestionmodel",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
