# Generated by Django 5.2.8 on 2025-11-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0007_remove_suggestionscachemodel_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestionmodel",
            name="total_rating_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="suggestionmodel",
            name="total_ratings",
            field=models.IntegerField(default=0),
        ),
    ]
