# Generated by Django 5.2.8 on 2025-11-07 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0008_suggestionmodel_total_rating_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suggestionscachemodel",
            old_name="suggestions_ids",
            new_name="suggestions",
        ),
    ]
