# Generated by Django 5.2.8 on 2025-11-06 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0008_suggestionmodel_total_rating_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestionmodel",
            name="total_rating_score",
        ),
        migrations.RemoveField(
            model_name="suggestionmodel",
            name="total_ratings",
        ),
    ]
