# Generated by Django 5.2.8 on 2025-11-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "suggestions",
            "0009_rename_suggestions_ids_suggestionscachemodel_suggestions",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="suggestionscachemodel",
            old_name="suggestions",
            new_name="suggestion_ids",
        ),
    ]
