# Generated by Django 5.2.8 on 2025-11-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0010_rename_suggestions_suggestionscachemodel_suggestion_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestionmodel",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
