# Generated by Django 5.2.8 on 2025-11-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0011_suggestionmodel_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestionscachemodel",
            name="suggestion_ids",
        ),
        migrations.AddField(
            model_name="suggestionscachemodel",
            name="suggestions",
            field=models.JSONField(default=dict),
        ),
    ]
