# Generated by Django 5.2.8 on 2025-11-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0012_remove_suggestionscachemodel_suggestion_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestionmodel",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
