# Generated by Django 5.2.8 on 2025-11-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0013_suggestionmodel_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestionmodel",
            name="score",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="suggestionscachemodel",
            name="suggestions",
            field=models.JSONField(default=list),
        ),
    ]
