# Generated by Django 5.2.8 on 2025-11-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0014_alter_suggestionmodel_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestionmodel",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
