# Generated by Django 5.2.8 on 2025-11-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0008_suggestionmodel_tags"),
        ("suggestions", "0015_alter_suggestionmodel_score"),
    ]

    operations = []
