# Generated by Django 5.2.8 on 2025-11-08 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0009_remove_suggestionmodel_total_rating_score_and_more"),
        ("suggestions", "0016_merge_20251108_1525"),
    ]

    operations = []
