# Generated by Django 5.2.8 on 2025-11-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrating",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
