# Generated by Django 5.2.8 on 2025-11-13 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_rename_usermodel_userprofile"),
        ("social", "0002_userrating_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrating",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.userprofile"),
        ),
    ]
