# Generated by Django 5.2.8 on 2025-11-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_remove_userprofile_email_alter_userprofile_user"),
        ("social", "0004_alter_userrating_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrating",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.userprofile"),
        ),
    ]
