# Generated by Django 5.2.8 on 2025-11-16 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0005_alter_userrating_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrating",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userrating",
            name="image",
            field=models.ImageField(blank=True, default=None, null=True, upload_to="uploads/"),
        ),
    ]
