# Generated by Django 5.2.8 on 2025-11-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0006_userrating_created_at_userrating_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrating",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
